// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_bloodRequestPage.cpp"
#include "EWIEGA46WW/moc_bloodbank.cpp"
#include "EWIEGA46WW/moc_forgotpassword.cpp"
#include "EWIEGA46WW/moc_recipientPage.cpp"
#include "EWIEGA46WW/moc_signup.cpp"
